name: EduGuide
version: '3.8'

services:

  webapi:
    build:
      context: ../../../
      dockerfile: src/Gateway/EduGuide.Gateway/Dockerfile
    container_name: EduGuide
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=EduGuide;User Id=sa;Password=@EduGuide04;TrustServerCertificate=True;Encrypt=False;
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - sqlserver
      - redis
      - minio
    networks:
      - app-network
    sysctls: 
      net.ipv6.conf.all.disable_ipv6: 0
      net.ipv6.conf.all.forwarding: 1
    restart: always

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=@EduGuide04
    ports:
      - "1400:1433"
    networks:
      - app-network
    volumes:
      - sql-data:/var/opt/mssql
    restart: always

  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
    restart: always

  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  app-network:

volumes:
  sql-data:
  minio-data:
